# Generated by Django 3.0.5 on 2020-05-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_mgmt', '0003_auto_20200503_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
    ]
